version: '3.8'

services:
  nuxt:
    container_name: nuxt
    image: nuxt_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/app/frontend
      - /frontend/node_modules
    ports:
      - 3000:3000
      - "24678:24678"
    command: yarn dev
    restart: always